// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const innerHeader: string;
export const buttonsContainer: string;
export const linksContainer: string;
export const header: string;
export const headerText: string;
